permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  
title: hereticalbooks.com
url: https://hereticalbooks.com
baseurl: ""
description: "Personal Website of Ralph Perrier"
author: Ralph Perrier
twitter: 
email: admin@hereticalbooks.com

timezone: Europe/Madrid
google_analytics_tracking_id: G-FXG5NPC273
