permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  
title: ralphperrier.org
url: https://www.ralphperrier.org
baseurl: ""
description: "Personal website of Ralph Perrier"
author: Ralph Perrier
twitter: 
email: admin@ralphperrier.org

timezone: Europe/Madrid
google_analytics_tracking_id: G-J8J1H8BR6R
