permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-minifier
  
title: lunalucifera.org
url: https://www.lunalucifera.org
baseurl: ""
description: "Personal website of Hugo Pepe"
author: Hugo
twitter: 
email: admin@lunalucifera.org

timezone: Europe/Madrid
google_analytics_tracking_id: G-J8J1H8BR6R
