permalink: /:title/
plugins:
  - jekyll-sitemap

title: christcuck.org
url: https://christcuck.org
baseurl: ""
description: "Personal website of Hugo Pepe"
author: Hugo
twitter: 
email: christcuck@christcuck.org

timezone: Europe/Madrid
google_analytics_tracking_id:
